manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: northisup
      url-base: https://github.com/NorthIsUp
  projects:
    - name: zmk
      remote: northisup
      revision: zmk-v0.3.0-191-g9ebbeff0-adv360.1
      import: app/west.yml
  self:
    path: config
